#define DISP_GPIO_TP_CS 7
#define DISP_GPIO_LCD_CS 8
#define DISP_GPIO_LCD_MISO 9
#define DISP_GPIO_LCD_MOSI 10
#define DISP_GPIO_LCD_SCLK 11
#define DISP_GPIO_LCD_RS 24
#define DISP_GPIO_RESET 25
#define DISP_GPIO_TP_IRQ 11
#define DISP_GPIO_BACKLIGHT 18

static void DispInit(void)
{
	GpioSelectFunction(DISP_GPIO_TP_CS, GPIO_FUNCTION_ALT0);
	GpioSelectFunction(DISP_GPIO_LCD_CS, GPIO_FUNCTION_ALT0);
	GpioSelectFunction(DISP_GPIO_LCD_MISO, GPIO_FUNCTION_ALT0);
	GpioSelectFunction(DISP_GPIO_LCD_MOSI, GPIO_FUNCTION_ALT0);
	GpioSelectFunction(DISP_GPIO_LCD_SCLK, GPIO_FUNCTION_ALT0);
	GpioSelectFunction(DISP_GPIO_LCD_RS, GPIO_FUNCTION_OUTPUT);
	GpioSelectFunction(DISP_GPIO_RESET, GPIO_FUNCTION_OUTPUT);
	GpioSelectFunction(DISP_GPIO_TP_IRQ, GPIO_FUNCTION_INPUT);
	GpioSelectFunction(DISP_GPIO_BACKLIGHT, GPIO_FUNCTION_OUTPUT);

	GpioControlPull(DISP_GPIO_TP_CS, GPIO_PULL_OFF);
	GpioControlPull(DISP_GPIO_LCD_CS, GPIO_PULL_OFF);
	GpioControlPull(DISP_GPIO_LCD_MISO, GPIO_PULL_OFF);
	GpioControlPull(DISP_GPIO_LCD_MOSI, GPIO_PULL_OFF);
	GpioControlPull(DISP_GPIO_LCD_SCLK, GPIO_PULL_OFF);
	GpioControlPull(DISP_GPIO_LCD_RS, GPIO_PULL_OFF);
	GpioControlPull(DISP_GPIO_RESET, GPIO_PULL_OFF);
	GpioControlPull(DISP_GPIO_TP_IRQ, GPIO_PULL_UP);
	GpioControlPull(DISP_GPIO_BACKLIGHT, GPIO_PULL_OFF);
}
